### ISSUE TITLE
Dataset arrangements

### ISSUE THREAD

**Issue by ZhengdiYu** [rotem-shalev/Ham2Pose#1]
Hi,

Thank you for your amazing work!

I would like to know more about the dataset layout that you used in the paper. You have mentioned 4 datasets in the paper but I only found 2 in the code. 

Also, will there be a guideline on how to organize the dataset for training your method? (e.g. How to download, data format, path)

Many thanks,

**Comment by rotem-shalev** [comment]
Hi Zhengdi,
I used 3 datasets that contain 4 languages together:
1.  [The DGS Corpus](https://www.sign-lang.uni-hamburg.de/dgs-korpus/)
2.  [Dicta-Sign](https://www.sign-lang.uni-hamburg.de/dicta-sign/portal/concepts/concepts_eng.html)
3. [The corpus-based dictionary of Polish Sign Language](https://www.slownikpjm.uw.edu.pl/en).

The HamNoSys notations and links to the original videos are in [data.json](https://github.com/rotem-shalev/Ham2Pose/blob/main/data/hamnosys/data.json) and the extracted pose estimations are in [keypoints.zip](https://github.com/rotem-shalev/Ham2Pose/blob/main/data/hamnosys/keypoints.zip) so for training over this data all you need to do is run train.py. 

Note that the trained model is also available under [model.ckpt](https://github.com/rotem-shalev/Ham2Pose/blob/main/models/ham2pose/checkpoints/model.ckpt).

**Comment by ZhengdiYu** [comment]
Thank you for your reply! This is really helpful.
