### ISSUE TITLE
Saving Ham2Pose as json files

### ISSUE THREAD

**Issue by leetcodevis13** [rotem-shalev/Ham2Pose#3]
Hi authors, 
Thank you for sharing your remarkable code base. I was trying to get the coco keypoints in json formats (similar to openpose outputs). But I am finding hard to extract it because of the pose_format library module. Can you guide me in getting the json file for every frame ?

**Comment by rotem-shalev** [comment]
Hi,
Can you share what was the problem with the pose_format library exactly?
Maybe also add a sample of the data that you are trying to convert into the per-frame json format.

**Comment by leetcodevis13** [comment]
Thanks the suggestion worked
